name: base-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - lckr-jupyterlab-variableinspector
    - pandas
    - matplotlib
    - scipy
    - pyproj
    - netCDF4
    - sklearn
    - ipympl
